name: Scrape Website

on:
  schedule:
    - cron: '*/30 */20 * * *'  # každou minutu
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore & Build
        run: dotnet build

      - name: Run Scraper
        run: dotnet run        
        
      - name: Run a multi-line script
        run: |
          echo end.
          echo success.
