name: Scrape Website

on:
  schedule:
    - cron: '15 8,12,16,20 * * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: dotnet build

      - name: Run Scraper
        run: dotnet run --project EdeskyScraper

      - name: Commit and push
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions" || echo "Nothing to commit"
          git push
          echo success.
          
