name: Scrape Website

on:
  schedule:
    - cron: '30 20 * * *'  # at 20:30 utc
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: s
        uses: actions/checkout@v4
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: create file
        run: |
          echo "Hello from GitHub Actions!" >> hello.txt
      
      - name: Commit and push
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions" || echo "Nothing to commit"
          git push
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: dotnet build

      - name: Run Scraper
        run: dotnet run --project EdeskyScraper
        
      - name: Run a multi-line script
        run: |
          echo end.
          echo success.
